version: '3'
services:
  local-jenkins:
    build: ./local-jenkins
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./.jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8089:8080
  registry:
    image: registry:2
    ports:
      - 5000:5000
